import { GameAccess } from '@prisma/client';

export const FREE_GAMES = [
  {
    slug: 'space-defender',
    title: 'Space Defender',
    description: 'Defend the orbital ring from waves of neon invaders. Original arcade shooter.',
    tagline: 'Hold the perimeter',
    genres: ['Arcade', 'Action', 'Sci-Fi'],
    tags: ['shooter', 'waves'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: true,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'pixel-runner',
    title: 'Pixel Runner',
    description: 'Dash through procedural neon cities. Jump, slide, survive forever.',
    genres: ['Arcade', 'Platformer'],
    tags: ['runner', 'endless'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: true,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'galaxy-assault',
    title: 'Galaxy Assault',
    description: 'Top-down starfield combat with escalating fleets.',
    genres: ['Action', 'Sci-Fi'],
    tags: ['shooter'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'snake-evolution',
    title: 'Snake Evolution',
    description: 'Grow, mutate, and outmaneuver in a glowing grid arena.',
    genres: ['Arcade', 'Idle'],
    tags: ['classic'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'brick-destroyer',
    title: 'Brick Destroyer',
    description: 'Shatter luminous brick formations with precision paddles.',
    genres: ['Arcade', 'Puzzle'],
    tags: ['paddle'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'maze-escape',
    title: 'Maze Escape',
    description: 'Procedural labyrinths that rewrite themselves each run.',
    genres: ['Adventure', 'Puzzle'],
    tags: ['maze', 'procedural'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: true,
    trending: false,
    endlessStory: true,
  },
  {
    slug: 'tank-arena',
    title: 'Tank Arena',
    description: 'Tactical arena duels with destructible neon cover.',
    genres: ['Action', 'Strategy'],
    tags: ['arena'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'alien-blaster',
    title: 'Alien Blaster',
    description: 'Rapid-fire insectoid swarms across crystalline caverns.',
    genres: ['Action', 'Horror'],
    tags: ['blaster'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'sky-shooter',
    title: 'Sky Shooter',
    description: 'Soar through storm fronts and clear the skies.',
    genres: ['Arcade', 'Action'],
    tags: ['flight'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'fruit-slice',
    title: 'Fruit Slice',
    description: 'Slice cascading fruit orbs — miss the void bombs.',
    genres: ['Arcade'],
    tags: ['reflex'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'tower-defender',
    title: 'Tower Defender',
    description: 'Place energy towers and hold the lane forever.',
    genres: ['Strategy', 'Survival'],
    tags: ['tower'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: true,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'endless-racer',
    title: 'Endless Racer',
    description: 'Neon highway racing with reactive traffic patterns.',
    genres: ['Racing', 'Arcade'],
    tags: ['racing'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'zombie-survival',
    title: 'Zombie Survival',
    description: 'Nightfall horde survival with crafting scraps.',
    genres: ['Survival', 'Horror', 'Action'],
    tags: ['survival'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'word-puzzle',
    title: 'Word Puzzle',
    description: 'Assemble luminous letters into cascading words.',
    genres: ['Puzzle'],
    tags: ['words'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'sudoku',
    title: 'Sudoku',
    description: 'Classic number grids with elegant neon UI.',
    genres: ['Puzzle'],
    tags: ['logic'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'chess',
    title: 'Chess',
    description: 'Original chess ruleset with cinematic board lighting.',
    genres: ['Strategy', 'Puzzle'],
    tags: ['board'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: true,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'checkers',
    title: 'Checkers',
    description: 'Fast checkers duels on a glowing checkerboard.',
    genres: ['Strategy'],
    tags: ['board'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'twenty-forty-eight',
    title: '2048',
    description: 'Merge luminous tiles toward 2048 and beyond.',
    genres: ['Puzzle'],
    tags: ['merge'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'bubble-pop',
    title: 'Bubble Pop',
    description: 'Aim and pop chromatic bubble clusters.',
    genres: ['Puzzle', 'Arcade'],
    tags: ['bubbles'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'memory-match',
    title: 'Memory Match',
    description: 'Match pairs of original neon sigils.',
    genres: ['Puzzle'],
    tags: ['memory'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
].map((g) => ({ ...g, tags: g.tags, creditCost: 0, published: true, hidden: false, version: '1.0.0' }));

/** Expandable premium catalog stubs (200+ scalable pattern) */
export const PREMIUM_GAME_SEEDS = Array.from({ length: 40 }, (_, i) => {
  const n = i + 1;
  const genres = [
    ['Adventure', 'Fantasy'],
    ['RPG', 'Fantasy'],
    ['Sci-Fi', 'Action'],
    ['Horror', 'Survival'],
    ['Racing', 'Arcade'],
    ['Strategy', 'Simulation'],
    ['MMORPG', 'Fantasy'],
    ['Idle', 'Simulation'],
  ][n % 8];
  return {
    slug: `premium-realm-${n}`,
    title: `Realm ${n}: ${['Aether', 'Nyx', 'Quasar', 'Obsidian', 'Lumen'][n % 5]} Chronicles`,
    description: `Premium endless adventure #${n}. Procedural kingdoms, AI NPCs, no final ending.`,
    tagline: 'The story never finishes',
    genres,
    tags: ['premium', 'endless'],
    access: n % 3 === 0 ? GameAccess.CREDITS : GameAccess.PREMIUM,
    creditCost: n % 3 === 0 ? 25 + (n % 5) * 10 : 0,
    engine: 'canvas',
    featured: n <= 3,
    trending: n <= 8,
    endlessStory: genres.includes('Adventure') || genres.includes('RPG'),
    published: true,
    hidden: false,
    version: '1.0.0',
  };
});

export const ACHIEVEMENTS = [
  { key: 'first_play', title: 'First Light', description: 'Play your first game', icon: 'spark', xpReward: 50, coinReward: 25 },
  { key: 'streak_7', title: 'Week Walker', description: 'Claim 7 daily rewards', icon: 'flame', xpReward: 200, coinReward: 100 },
  { key: 'score_10k', title: 'Pulse Master', description: 'Reach 10,000 score in any game', icon: 'crown', xpReward: 150, coinReward: 75 },
  { key: 'premium_join', title: 'Forever Player', description: 'Join Premium', icon: 'diamond', xpReward: 300, coinReward: 0 },
  { key: 'friends_5', title: 'Squad Signal', description: 'Add 5 friends', icon: 'users', xpReward: 100, coinReward: 50 },
];
