import { GameAccess } from '@prisma/client';
import { SIGNATURE_ORIGINALS, buildExpandedCatalog } from './catalog/jgames-200';

export const FREE_GAMES = [
  {
    slug: 'space-defender',
    title: 'Space Defender',
    description: 'Defend the orbital ring from waves of neon invaders. Original arcade shooter.',
    tagline: 'Hold the perimeter',
    genres: ['Arcade', 'Action', 'Sci-Fi'],
    tags: ['shooter', 'waves'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: true,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'pixel-runner',
    title: 'Pixel Runner',
    description: 'Dash through procedural neon cities. Jump, slide, survive forever.',
    genres: ['Arcade', 'Platformer'],
    tags: ['runner', 'endless'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: true,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'galaxy-assault',
    title: 'Galaxy Assault',
    description: 'Top-down starfield combat with escalating fleets.',
    genres: ['Action', 'Sci-Fi'],
    tags: ['shooter'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'snake-evolution',
    title: 'Snake Evolution',
    description: 'Grow, mutate, and outmaneuver in a glowing grid arena.',
    genres: ['Arcade', 'Idle'],
    tags: ['classic'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'brick-destroyer',
    title: 'Brick Destroyer',
    description: 'Shatter luminous brick formations with precision paddles.',
    genres: ['Arcade', 'Puzzle'],
    tags: ['paddle'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'maze-escape',
    title: 'Maze Escape',
    description: 'Procedural labyrinths that rewrite themselves each run.',
    genres: ['Adventure', 'Puzzle'],
    tags: ['maze', 'procedural'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: true,
    trending: false,
    endlessStory: true,
  },
  {
    slug: 'tank-arena',
    title: 'Tank Arena',
    description: 'Tactical arena duels with destructible neon cover.',
    genres: ['Action', 'Strategy'],
    tags: ['arena'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'alien-blaster',
    title: 'Alien Blaster',
    description: 'Rapid-fire insectoid swarms across crystalline caverns.',
    genres: ['Action', 'Horror'],
    tags: ['blaster'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'sky-shooter',
    title: 'Sky Shooter',
    description: 'Soar through storm fronts and clear the skies.',
    genres: ['Arcade', 'Action'],
    tags: ['flight'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'fruit-slice',
    title: 'Fruit Slice',
    description: 'Slice cascading fruit orbs — miss the void bombs.',
    genres: ['Arcade'],
    tags: ['reflex'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'tower-defender',
    title: 'Tower Defender',
    description: 'Place energy towers and hold the lane forever.',
    genres: ['Strategy', 'Survival'],
    tags: ['tower'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: true,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'endless-racer',
    title: 'Endless Racer',
    description: 'Neon highway racing with reactive traffic patterns.',
    genres: ['Racing', 'Arcade'],
    tags: ['racing'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'zombie-survival',
    title: 'Zombie Survival',
    description: 'Nightfall horde survival with crafting scraps.',
    genres: ['Survival', 'Horror', 'Action'],
    tags: ['survival'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'word-puzzle',
    title: 'Word Puzzle',
    description: 'Assemble luminous letters into cascading words.',
    genres: ['Puzzle'],
    tags: ['words'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'sudoku',
    title: 'Sudoku',
    description: 'Classic number grids with elegant neon UI.',
    genres: ['Puzzle'],
    tags: ['logic'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'chess',
    title: 'Chess',
    description: 'Original chess ruleset with cinematic board lighting.',
    genres: ['Strategy', 'Puzzle'],
    tags: ['board'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: true,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'checkers',
    title: 'Checkers',
    description: 'Fast checkers duels on a glowing checkerboard.',
    genres: ['Strategy'],
    tags: ['board'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'twenty-forty-eight',
    title: '2048',
    description: 'Merge luminous tiles toward 2048 and beyond.',
    genres: ['Puzzle'],
    tags: ['merge'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    slug: 'bubble-pop',
    title: 'Bubble Pop',
    description: 'Aim and pop chromatic bubble clusters.',
    genres: ['Puzzle', 'Arcade'],
    tags: ['bubbles'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    slug: 'memory-match',
    title: 'Memory Match',
    description: 'Match pairs of original neon sigils.',
    genres: ['Puzzle'],
    tags: ['memory'],
    access: GameAccess.FREE,
    engine: 'canvas',
    featured: false,
    trending: false,
    endlessStory: false,
  },
].map((g) => ({ ...g, tags: g.tags, creditCost: 0, published: true, hidden: false, version: '1.0.0' }));

const classicSlugs = FREE_GAMES.map((g) => g.slug);

const expanded = buildExpandedCatalog(classicSlugs);

/** Signature originals + expandable premium catalog (~180) */
export const PREMIUM_GAME_SEEDS = expanded
  .filter((g) => !classicSlugs.includes(g.slug))
  .map((g) => ({
    slug: g.slug,
    title: g.title,
    description: g.description,
    tagline: g.tagline,
    genres: g.genres,
    tags: g.tags,
    access: g.access === 'FREE' ? GameAccess.FREE : g.access === 'CREDITS' ? GameAccess.CREDITS : GameAccess.PREMIUM,
    creditCost: g.creditCost,
    engine: g.engine,
    featured: !!g.featured,
    trending: !!g.trending,
    endlessStory: !!g.endlessStory,
    published: true,
    hidden: false,
    version: '1.0.0',
  }));

/** Ensure signature free titles are also in FREE_GAMES-style seed via PREMIUM list if access FREE */
export const SIGNATURE_FREE_SEEDS = SIGNATURE_ORIGINALS.filter((g) => g.access === 'FREE').map((g) => ({
  slug: g.slug,
  title: g.title,
  description: g.description,
  tagline: g.tagline,
  genres: g.genres,
  tags: g.tags,
  access: GameAccess.FREE,
  creditCost: 0,
  engine: g.engine,
  featured: !!g.featured,
  trending: !!g.trending,
  endlessStory: !!g.endlessStory,
  published: true,
  hidden: false,
  version: '1.0.0',
}));

export const ALL_SEED_GAMES = [...FREE_GAMES, ...SIGNATURE_FREE_SEEDS, ...PREMIUM_GAME_SEEDS.filter((g) => g.access !== GameAccess.FREE)];

export const ACHIEVEMENTS = [
  { key: 'first_play', title: 'First Light', description: 'Play your first game', icon: 'spark', xpReward: 50, coinReward: 25 },
  { key: 'streak_7', title: 'Week Walker', description: 'Claim 7 daily rewards', icon: 'flame', xpReward: 200, coinReward: 100 },
  { key: 'score_10k', title: 'Pulse Master', description: 'Reach 10,000 score in any game', icon: 'crown', xpReward: 150, coinReward: 75 },
  { key: 'premium_join', title: 'Forever Player', description: 'Join Premium', icon: 'diamond', xpReward: 300, coinReward: 0 },
  { key: 'friends_5', title: 'Squad Signal', description: 'Add 5 friends', icon: 'users', xpReward: 100, coinReward: 50 },
  { key: 'ashvale_chief', title: 'Chief of Ashvale', description: 'Become Chief in Rise of the Forgotten King', icon: 'staff', xpReward: 250, coinReward: 100 },
  { key: 'endless_frontier', title: 'Endless Frontier', description: 'Reach Frontier 5 in Story Mode', icon: 'map', xpReward: 400, coinReward: 150 },
];
