/**
 * ~160 original expandable JGames titles — cross-generation appeal.
 * Completely original concepts (not copies of existing games).
 */

export type ExpandedTitle = {
  title: string;
  slug?: string;
  description: string;
  tagline?: string;
  genres: string[];
  tags: string[];
  endlessStory?: boolean;
};

export const EXPANDED_TITLES: ExpandedTitle[] = [
  // Family & casual
  { title: 'Sunny Farm Friends', description: 'Tend crops, pets, and seasonal festivals with the whole family.', genres: ['Simulation', 'Idle'], tags: ['family', 'farm'] },
  { title: 'Kitchen Quest Kids', description: 'Cook colorful recipes against the clock — no fire, all fun.', genres: ['Puzzle', 'Arcade'], tags: ['family', 'cooking'] },
  { title: 'Balloon Parade Rally', description: 'Float through carnival skies popping only the right balloons.', genres: ['Arcade', 'Platformer'], tags: ['kids', 'casual'] },
  { title: 'Grandma’s Garden Maze', description: 'Gentle labyrinth walks collecting herbs before sunset.', genres: ['Puzzle', 'Adventure'], tags: ['casual', 'cozy'] },
  { title: 'Pet Parade Park', description: 'Train adorable original pets for park shows and ribbons.', genres: ['Simulation', 'Sports'], tags: ['pets', 'family'] },
  { title: 'Color Cascade Calm', description: 'Match soft hues in a soothing endless cascade.', genres: ['Puzzle', 'Idle'], tags: ['relax', 'casual'] },
  { title: 'Storytime Stars', description: 'Choose bedtime adventure paths that rewrite themselves nightly.', genres: ['Adventure', 'RPG'], tags: ['kids', 'story'], endlessStory: true },
  { title: 'Paper Plane World Tour', description: 'Fold, throw, and glide paper planes across landmark skies.', genres: ['Arcade', 'Sports'], tags: ['casual'] },
  { title: 'Block Castle Builders', description: 'Stack sturdy towers before the wind knocks them down.', genres: ['Puzzle', 'Simulation'], tags: ['kids', 'building'] },
  { title: 'Melody Meadow', description: 'Compose tunes by tapping glowing flowers in rhythm.', genres: ['Arcade', 'Puzzle'], tags: ['music', 'family'] },
  // Teen / action
  { title: 'Rooftop Relay', description: 'Parkour across neon rooftops delivering packages on time.', genres: ['Action', 'Platformer'], tags: ['parkour'] },
  { title: 'Hoverboard Havoc', description: 'Grind rails through megacity districts with trick combos.', genres: ['Sports', 'Arcade'], tags: ['extreme'] },
  { title: 'Esports Arena Pulse', description: '5v5 arena drafts with cosmetics-only loadouts.', genres: ['Action', 'Sports'], tags: ['arena', 'multi'] },
  { title: 'Skate Mirage', description: 'Street sessions in mirage cities that reshape each night.', genres: ['Sports', 'Arcade'], tags: ['skate'] },
  { title: 'Drift Circuit Zero', description: 'Perfect drifts on ice, sand, and glass highways.', genres: ['Racing', 'Arcade'], tags: ['drift'] },
  { title: 'Laser Tag Legends', description: 'Capture flags in holographic warehouses.', genres: ['Action', 'Sports'], tags: ['laser'] },
  { title: 'VR Dojo Trials', description: 'Master combo strings in a virtual martial arts dojo.', genres: ['Action', 'Arcade'], tags: ['martial'] },
  { title: 'Graffiti Run', description: 'Tag walls, dodge security drones, escape the district.', genres: ['Action', 'Platformer'], tags: ['urban'] },
  { title: 'Brawl Bazaar', description: 'Friendly tournament brawls with wild stage hazards.', genres: ['Action', 'Arcade'], tags: ['brawler'] },
  { title: 'Synthwave Skirmish', description: 'Side-scroll blasters through retro-future alleys.', genres: ['Action', 'Arcade'], tags: ['shooter'] },
  // Adults / strategy / sims
  { title: 'Metro Manager 2049', description: 'Balance transit lines, budgets, and rush-hour chaos.', genres: ['Simulation', 'Strategy'], tags: ['city'] },
  { title: 'Boardroom Blitz', description: 'Negotiate deals, hire talent, and outpace rival firms.', genres: ['Strategy', 'Simulation'], tags: ['business'] },
  { title: 'Quiet Cafe Stories', description: 'Serve coffee, listen to patrons, unlock life chapters.', genres: ['Simulation', 'Adventure'], tags: ['cozy'], endlessStory: true },
  { title: 'Island Architect', description: 'Design eco-islands with tourism and wildlife balance.', genres: ['Simulation', 'Strategy'], tags: ['builder'] },
  { title: 'Courtroom Logic', description: 'Present evidence, cross-examine, and win cases.', genres: ['Puzzle', 'Adventure'], tags: ['mystery'] },
  { title: 'Stock Signal', description: 'Read markets of a fictional galaxy exchange.', genres: ['Strategy', 'Simulation'], tags: ['economy'] },
  { title: 'Hospital Night Shift', description: 'Triage patients through escalating overnight waves.', genres: ['Simulation', 'Strategy'], tags: ['hospital'] },
  { title: 'Newsroom Deadline', description: 'Assign reporters, chase leads, publish before rivals.', genres: ['Strategy', 'Simulation'], tags: ['media'] },
  { title: 'Museum After Dark', description: 'Curate exhibits and stop artifact thieves at night.', genres: ['Adventure', 'Puzzle'], tags: ['heist'] },
  { title: 'Orbit Colony Ops', description: 'Keep a space habitat alive with limited oxygen and morale.', genres: ['Simulation', 'Sci-Fi'], tags: ['colony'] },
  // RPG / story
  { title: 'Lantern of Elaris', description: 'Carry a living lantern through kingdoms that forget their names.', genres: ['RPG', 'Fantasy', 'Adventure'], tags: ['story'], endlessStory: true },
  { title: 'Ashborn Chronicle', description: 'Rebuild a fallen order through branching oaths.', genres: ['RPG', 'Fantasy'], tags: ['story'], endlessStory: true },
  { title: 'Tidebound Knights', description: 'Knightly quests that change with the ocean tides.', genres: ['RPG', 'Adventure'], tags: ['knights'], endlessStory: true },
  { title: 'Crystal Pact', description: 'Form pacts with spirit crystals to reshape battlefields.', genres: ['RPG', 'Strategy'], tags: ['magic'] },
  { title: 'Nomad of Nine Moons', description: 'Travel caravan routes under shifting moon laws.', genres: ['RPG', 'Adventure'], tags: ['travel'], endlessStory: true },
  { title: 'Guild of Broken Maps', description: 'Assemble map shards that rewrite dungeon layouts.', genres: ['RPG', 'Adventure'], tags: ['dungeon'], endlessStory: true },
  { title: 'Soulforge Apprentice', description: 'Craft legendary gear by tempering memories into steel.', genres: ['RPG', 'Simulation'], tags: ['crafting'] },
  { title: 'Echoes of Velmora', description: 'Speak with echoes of past heroes to alter futures.', genres: ['RPG', 'Adventure'], tags: ['time'], endlessStory: true },
  { title: 'Beastbond Academy', description: 'Bond with original beasts and graduate through trials.', genres: ['RPG', 'Adventure'], tags: ['creatures'] },
  { title: 'Crownless Heirs', description: 'Rival heirs negotiate, duel, and rule contested lands.', genres: ['RPG', 'Strategy'], tags: ['politics'], endlessStory: true },
  // Horror / survival
  { title: 'Fog Station 13', description: 'Repair a train station swallowed by living fog.', genres: ['Horror', 'Survival'], tags: ['fog'] },
  { title: 'Blackout Basement', description: 'Navigate pitch-black floors with a dying flashlight.', genres: ['Horror', 'Puzzle'], tags: ['stealth'] },
  { title: 'Harvest Night', description: 'Defend the farm when scarecrows start walking.', genres: ['Horror', 'Survival'], tags: ['farm'] },
  { title: 'Signal Lost', description: 'Follow radio static through an abandoned research town.', genres: ['Horror', 'Adventure'], tags: ['mystery'] },
  { title: 'Depths Below Harbor', description: 'Dive wrecks while something circles the light.', genres: ['Horror', 'Survival'], tags: ['ocean'] },
  { title: 'Cabin Protocol', description: 'Survive winter nights with dwindling wood and trust.', genres: ['Horror', 'Survival'], tags: ['winter'] },
  { title: 'Mirror Ward', description: 'Hospital wing where reflections act first.', genres: ['Horror', 'Puzzle'], tags: ['psychological'] },
  { title: 'Ashfall Shelter', description: 'Lead survivors after a volcanic nightfall.', genres: ['Survival', 'Strategy'], tags: ['disaster'] },
  { title: 'Crowfeast Fields', description: 'Reclaim crops from endless murder of crows.', genres: ['Survival', 'Action'], tags: ['rural'] },
  { title: 'Last Lighthouse', description: 'Keep the beam alive or the coast vanishes.', genres: ['Survival', 'Adventure'], tags: ['lighthouse'], endlessStory: true },
  // Sci-fi
  { title: 'Quantum Courier', description: 'Deliver packages across timelines that disagree.', genres: ['Sci-Fi', 'Action'], tags: ['time'] },
  { title: 'Mech Bay Alpha', description: 'Repair mechs between sorties on a frontier moon.', genres: ['Sci-Fi', 'Simulation'], tags: ['mechs'] },
  { title: 'Starlane Smuggler', description: 'Chart illegal routes while dodging patrol fleets.', genres: ['Sci-Fi', 'Adventure'], tags: ['space'] },
  { title: 'Terraform Tonight', description: 'Balance atmosphere, flora, and storms on a new world.', genres: ['Sci-Fi', 'Strategy'], tags: ['planet'] },
  { title: 'Android Memoirs', description: 'Recover memory chips to reclaim who you were.', genres: ['Sci-Fi', 'Adventure'], tags: ['story'], endlessStory: true },
  { title: 'Pulse Gate Racers', description: 'Warp-gate racing with gravity hazards.', genres: ['Sci-Fi', 'Racing'], tags: ['racing'] },
  { title: 'Orbital Breach', description: 'Clear boarding parties deck by deck.', genres: ['Sci-Fi', 'Action'], tags: ['shooter'] },
  { title: 'Nanite Garden', description: 'Grow programmable matter into tools and defenses.', genres: ['Sci-Fi', 'Puzzle'], tags: ['nanites'] },
  { title: 'Comet Claim', description: 'Mine ice comets before rival crews arrive.', genres: ['Sci-Fi', 'Simulation'], tags: ['mining'] },
  { title: 'Void Choir', description: 'Decode songs from deep space that rewrite physics.', genres: ['Sci-Fi', 'Puzzle'], tags: ['mystery'], endlessStory: true },
  // Sports & racing
  { title: 'Street Kick United', description: 'Pickup soccer across world plazas with style points.', genres: ['Sports', 'Arcade'], tags: ['soccer'] },
  { title: 'Court Kings 3v3', description: 'Fast basketball with signature original moves.', genres: ['Sports', 'Arcade'], tags: ['basketball'] },
  { title: 'Alpine Rush', description: 'Ski wild courses with weather that flips mid-run.', genres: ['Sports', 'Racing'], tags: ['ski'] },
  { title: 'Wave Riders League', description: 'Surf procedural oceans for championship heats.', genres: ['Sports', 'Arcade'], tags: ['surf'] },
  { title: 'Tabletop Titans', description: 'Arcade table tennis with power zones.', genres: ['Sports', 'Arcade'], tags: ['pingpong'] },
  { title: 'Arena Bowl Classic', description: 'Futuristic bowling with shifting lane gravity.', genres: ['Sports', 'Arcade'], tags: ['bowling'] },
  { title: 'Cycle City Sprint', description: 'Bike courier races through living traffic AI.', genres: ['Racing', 'Sports'], tags: ['bike'] },
  { title: 'Kart Canyon Clash', description: 'Family-friendly kart battles in canyon arenas.', genres: ['Racing', 'Arcade'], tags: ['kart', 'family'] },
  { title: 'Golf Galaxy', description: 'Put across low-gravity courses on distant moons.', genres: ['Sports', 'Arcade'], tags: ['golf'] },
  { title: 'Relay of Ages', description: 'Team relay where each runner is from a different era.', genres: ['Sports', 'Adventure'], tags: ['relay'] },
  // Puzzle & brain
  { title: 'Glyph Lock', description: 'Rotate ancient glyphs to open vault doors.', genres: ['Puzzle', 'Adventure'], tags: ['glyphs'] },
  { title: 'Circuit Whisper', description: 'Rewire silent boards without triggering alarms.', genres: ['Puzzle', 'Sci-Fi'], tags: ['circuits'] },
  { title: 'Wordforge', description: 'Forge words into weapons and bridges.', genres: ['Puzzle', 'Adventure'], tags: ['words'] },
  { title: 'Mirror Sudoku Towers', description: 'Classic logic grids stacked into vertical towers.', genres: ['Puzzle'], tags: ['sudoku'] },
  { title: 'Paint by Physics', description: 'Pour colors that obey gravity and bounce rules.', genres: ['Puzzle', 'Arcade'], tags: ['physics'] },
  { title: 'Clockwork Cubes', description: 'Disassemble wind-up cubes before they rewind.', genres: ['Puzzle'], tags: ['mechanical'] },
  { title: 'Language of Leaves', description: 'Translate forest symbols into safe paths.', genres: ['Puzzle', 'Adventure'], tags: ['nature'] },
  { title: 'Number Nebula', description: 'Merge cosmic digits toward ascending constellations.', genres: ['Puzzle', 'Arcade'], tags: ['numbers'] },
  { title: 'Shadow Tangrams', description: 'Cast correct silhouettes with limited shapes.', genres: ['Puzzle'], tags: ['tangram'] },
  { title: 'Echo Memory Palace', description: 'Remember room layouts that whisper changes.', genres: ['Puzzle', 'Horror'], tags: ['memory'] },
  // Strategy / tactics
  { title: 'Hex Dominion', description: 'Turn-based hex conquest with seasonal supply lines.', genres: ['Strategy'], tags: ['hex'] },
  { title: 'Siege of Glass', description: 'Attack and defend crystalline fortresses.', genres: ['Strategy', 'Action'], tags: ['siege'] },
  { title: 'Cardfront Command', description: 'Deck tactics where terrain cards reshape maps.', genres: ['Strategy', 'RPG'], tags: ['cards'] },
  { title: 'Colony Diplomacy', description: 'Win alliances without firing a shot — or fail loudly.', genres: ['Strategy', 'Simulation'], tags: ['diplomacy'] },
  { title: 'Tower Lattice', description: 'Link towers into lattices that amplify unique effects.', genres: ['Strategy', 'Arcade'], tags: ['tower'] },
  { title: 'Fleet Doctrine', description: 'Naval doctrine trees unlock new formation powers.', genres: ['Strategy', 'Sci-Fi'], tags: ['fleet'] },
  { title: 'Border Watch', description: 'Assign patrols across a living frontier map.', genres: ['Strategy', 'Simulation'], tags: ['tactics'] },
  { title: 'Resource Rift', description: 'Compete for rifts that spawn rare materials.', genres: ['Strategy', 'Idle'], tags: ['resources'] },
  { title: 'Automaton Uprising Plan', description: 'Outthink rogue factories before they mobilize.', genres: ['Strategy', 'Sci-Fi'], tags: ['robots'] },
  { title: 'Kingdom Ledger', description: 'Rule by spreadsheet: taxes, festivals, and revolts.', genres: ['Strategy', 'Simulation'], tags: ['kingdom'] },
  // Adventure / exploration
  { title: 'Lost Atlas Expedition', description: 'Fill blank maps that fight being completed.', genres: ['Adventure', 'RPG'], tags: ['exploration'], endlessStory: true },
  { title: 'Jungle Canopy Trail', description: 'Traverse living canopies with rope and wit.', genres: ['Adventure', 'Platformer'], tags: ['jungle'] },
  { title: 'Desert Mirage Caravan', description: 'Guide caravans through illusions and oasis politics.', genres: ['Adventure', 'Strategy'], tags: ['desert'], endlessStory: true },
  { title: 'Mountain Whisperers', description: 'Climb peaks that speak in weather.', genres: ['Adventure', 'Survival'], tags: ['climb'] },
  { title: 'River Kingdom Raft', description: 'Raft trade routes that flood into new chapters.', genres: ['Adventure', 'Simulation'], tags: ['river'], endlessStory: true },
  { title: 'Cave of Living Paint', description: 'Explore caves where murals become rooms.', genres: ['Adventure', 'Puzzle'], tags: ['caves'] },
  { title: 'Skybridge Nomads', description: 'Cross cloud bridges between migratory cities.', genres: ['Adventure', 'Fantasy'], tags: ['sky'], endlessStory: true },
  { title: 'Frozen Archive', description: 'Recover knowledge sealed under ice libraries.', genres: ['Adventure', 'Puzzle'], tags: ['ice'] },
  { title: 'Wildflower Road', description: 'A peaceful walking journey that blooms with choices.', genres: ['Adventure', 'Idle'], tags: ['cozy', 'walking'], endlessStory: true },
  { title: 'Portal Picnic', description: 'Family picnics across whimsical pocket dimensions.', genres: ['Adventure', 'Arcade'], tags: ['family', 'portal'] },
  // More cross-gen originals to fill ~160
  { title: 'Neon Bakery Tycoon', description: 'Bake glowing pastries for a night-city clientele.', genres: ['Simulation', 'Idle'], tags: ['bakery'] },
  { title: 'Robot Pet Rescue', description: 'Repair stray bots and find them homes.', genres: ['Adventure', 'Simulation'], tags: ['robots', 'family'] },
  { title: 'Pirate Market Day', description: 'Haggle, stock stalls, and dodge rival crews.', genres: ['Simulation', 'Adventure'], tags: ['pirates'] },
  { title: 'Wizard Homework Club', description: 'Finish magical assignments before the bell.', genres: ['Puzzle', 'Fantasy'], tags: ['magic', 'kids'] },
  { title: 'Samurai Garden Defense', description: 'Protect a zen garden with precise strikes.', genres: ['Action', 'Strategy'], tags: ['samurai'] },
  { title: 'Cowboy Courier', description: 'Deliver mail across dusty trails on horseback.', genres: ['Adventure', 'Racing'], tags: ['western'] },
  { title: 'Deep Sea Radio', description: 'Broadcast hope from a submarine station.', genres: ['Adventure', 'Simulation'], tags: ['ocean'], endlessStory: true },
  { title: 'Cloud Shepherd', description: 'Herd weather clouds to water thirsty lands.', genres: ['Simulation', 'Fantasy'], tags: ['weather', 'cozy'] },
  { title: 'Pixel Orchestra', description: 'Conduct an orchestra of living instruments.', genres: ['Arcade', 'Puzzle'], tags: ['music'] },
  { title: 'Time Capsule Racers', description: 'Race while eras swap under your wheels.', genres: ['Racing', 'Adventure'], tags: ['time'] },
  { title: 'Knight School Recess', description: 'Friendly castleyard sports with foam lances.', genres: ['Sports', 'Arcade'], tags: ['kids', 'knights'] },
  { title: 'Detective Duck Agency', description: 'Solve cozy town mysteries with a duck detective.', genres: ['Puzzle', 'Adventure'], tags: ['family', 'mystery'] },
  { title: 'Volcano Village Keep', description: 'Evacuate and rebuild after each eruption cycle.', genres: ['Survival', 'Simulation'], tags: ['volcano'], endlessStory: true },
  { title: 'Ice Cream Empire', description: 'Expand a cheerful dessert chain across seasons.', genres: ['Simulation', 'Idle'], tags: ['family', 'business'] },
  { title: 'Ninja Paper Fold', description: 'Origami stealth missions in a paper world.', genres: ['Action', 'Puzzle'], tags: ['ninja', 'kids'] },
  { title: 'Astronaut Chores', description: 'Complete space-station chores before systems fail.', genres: ['Simulation', 'Sci-Fi'], tags: ['space', 'casual'] },
  { title: 'Dragon Mail Service', description: 'Deliver parcels on young dragons across kingdoms.', genres: ['Adventure', 'Fantasy'], tags: ['dragons', 'family'] },
  { title: 'Haunted Library Cards', description: 'Catalog restless books before midnight.', genres: ['Horror', 'Puzzle'], tags: ['books'] },
  { title: 'Meadow Chess', description: 'Chess with living pieces that negotiate mid-match.', genres: ['Strategy', 'Fantasy'], tags: ['chess'] },
  { title: 'Bubble Sub Captain', description: 'Command a bubble sub through coral cities.', genres: ['Adventure', 'Arcade'], tags: ['ocean', 'kids'] },
  { title: 'Forge Festival', description: 'Craft festival prizes under cheering crowds.', genres: ['Simulation', 'Arcade'], tags: ['crafting'] },
  { title: 'Storm Chaser Dash', description: 'Photograph storms without getting caught.', genres: ['Racing', 'Adventure'], tags: ['weather'] },
  { title: 'Robot Ballet', description: 'Choreograph mechanical dancers for galactic stages.', genres: ['Arcade', 'Sports'], tags: ['dance', 'robots'] },
  { title: 'Fairy Transit Map', description: 'Connect fairy villages with glowing rail lines.', genres: ['Strategy', 'Fantasy'], tags: ['builder', 'family'] },
  { title: 'Moonlight Fishing', description: 'Catch rare fish that only bite under special moons.', genres: ['Simulation', 'Idle'], tags: ['fishing', 'cozy'] },
  { title: 'Castle Renovation', description: 'Restore a ruined castle room by room.', genres: ['Simulation', 'Puzzle'], tags: ['builder'] },
  { title: 'Alien Pen Pal', description: 'Exchange letters that unlock planetary quests.', genres: ['Adventure', 'Sci-Fi'], tags: ['story'], endlessStory: true },
  { title: 'Park Ranger Days', description: 'Protect trails, wildlife, and campers seasonally.', genres: ['Simulation', 'Adventure'], tags: ['nature'] },
  { title: 'Glowbug Catchers', description: 'Catch and release glowbugs to heal the forest.', genres: ['Arcade', 'Adventure'], tags: ['kids', 'nature'] },
  { title: 'Sandbox Siege Lite', description: 'Build tiny fortresses and test them against waves.', genres: ['Strategy', 'Arcade'], tags: ['builder'] },
  { title: 'Mystery Train Express', description: 'Solve passenger mysteries before the next station.', genres: ['Puzzle', 'Adventure'], tags: ['mystery'], endlessStory: true },
  { title: 'Hero Internship', description: 'Train as a junior hero doing neighborhood good deeds.', genres: ['Adventure', 'RPG'], tags: ['heroes', 'family'], endlessStory: true },
  { title: 'Crystal Cave Runner', description: 'Dash crystal tunnels that rearrange mid-sprint.', genres: ['Arcade', 'Platformer'], tags: ['runner'] },
  { title: 'Weather Wizard Wars', description: 'Duel with rain, sun, and snow spells.', genres: ['Action', 'Fantasy'], tags: ['magic'] },
  { title: 'Tiny Tactics Table', description: 'Pocket-sized army battles on a living tabletop.', genres: ['Strategy'], tags: ['miniatures'] },
  { title: 'Space Zoo Keepers', description: 'Care for alien animals with quirky needs.', genres: ['Simulation', 'Sci-Fi'], tags: ['zoo', 'family'] },
  { title: 'Rune Racer', description: 'Race on magical tracks drawn by runes you place.', genres: ['Racing', 'Fantasy'], tags: ['magic'] },
  { title: 'Silent Orchestra Heist', description: 'Steal a stolen symphony back note by note.', genres: ['Action', 'Adventure'], tags: ['heist', 'music'] },
  { title: 'Campfire Legends', description: 'Tell tales that become playable nights.', genres: ['Adventure', 'RPG'], tags: ['story', 'cozy'], endlessStory: true },
  { title: 'Pixel Plumber Pro', description: 'Fix pipes in cartoon cities before floods.', genres: ['Puzzle', 'Arcade'], tags: ['pipes', 'casual'] },
  { title: 'Hover Farm 3000', description: 'Farm in zero-g greenhouses above Earth.', genres: ['Simulation', 'Sci-Fi'], tags: ['farm'] },
  { title: 'Mask Festival March', description: 'Lead parade floats and keep spirits joyful.', genres: ['Simulation', 'Arcade'], tags: ['festival', 'family'] },
  { title: 'Thunder Drum Band', description: 'Rhythm battles with storm percussion.', genres: ['Arcade', 'Sports'], tags: ['music', 'rhythm'] },
  { title: 'Ice Fortress Architect', description: 'Sculpt ice walls that melt under pressure.', genres: ['Strategy', 'Puzzle'], tags: ['ice', 'builder'] },
  { title: 'Wanderbot Diary', description: 'A lonely robot journals worlds it discovers.', genres: ['Adventure', 'Idle'], tags: ['robots', 'story'], endlessStory: true },
  { title: 'Crown Jewel Caper', description: 'Plan heists with gadgets and timing puzzles.', genres: ['Puzzle', 'Action'], tags: ['heist'] },
  { title: 'Meadow Mayhem Soccer', description: 'Animal soccer with chaotic power fields.', genres: ['Sports', 'Arcade'], tags: ['kids', 'soccer'] },
  { title: 'Starlight Lullaby', description: 'Guide sleepy constellations back to bed.', genres: ['Puzzle', 'Adventure'], tags: ['kids', 'cozy'] },
  { title: 'Frontier Pharmacy', description: 'Brew remedies for a growing pioneer town.', genres: ['Simulation', 'Strategy'], tags: ['western', 'cozy'] },
  { title: 'Airship Tea Party', description: 'Host tea parties while steering through storms.', genres: ['Simulation', 'Adventure'], tags: ['steampunk', 'family'] },
  { title: 'Dungeon Decorators', description: 'Redesign dungeons to be safer — and stylish.', genres: ['Simulation', 'Puzzle'], tags: ['builder', 'humor'] },
  { title: 'Photon Pinball', description: 'Pinball tables made of living light.', genres: ['Arcade'], tags: ['pinball'] },
  { title: 'Legacy Tree', description: 'Grow a family tree of heroes across generations.', genres: ['RPG', 'Simulation'], tags: ['legacy'], endlessStory: true },
  { title: 'Sandcastle Kingdom Wars', description: 'Tide-timed castle battles on the beach.', genres: ['Strategy', 'Arcade'], tags: ['kids', 'beach'] },
  { title: 'Night Market Magic', description: 'Trade charms under lanterns that rewrite prices.', genres: ['Adventure', 'Simulation'], tags: ['market'], endlessStory: true },
  { title: 'Guardian Beetle Race', description: 'Race giant beetles through jungle arenas.', genres: ['Racing', 'Adventure'], tags: ['bugs', 'kids'] },
  { title: 'Echo Tower Climb', description: 'Climb a tower that echoes your past runs.', genres: ['Platformer', 'Adventure'], tags: ['climb'], endlessStory: true },
  { title: 'Cosmic Chess Blitz', description: 'Speed chess on boards that fold into 3D.', genres: ['Strategy', 'Sci-Fi'], tags: ['chess'] },
  { title: 'Harvest Moonlight Fair', description: 'Run fair booths under a forever harvest moon.', genres: ['Simulation', 'Idle'], tags: ['festival', 'cozy'] },
  { title: 'Bolt & Brush', description: 'Repair street art robots that paint the city alive.', genres: ['Adventure', 'Puzzle'], tags: ['art', 'robots'] },
  { title: 'Phantom Orchestra Pit', description: 'Conduct ghosts to finish an unfinished symphony.', genres: ['Puzzle', 'Horror'], tags: ['music'] },
  { title: 'Valley of Soft Giants', description: 'Befriend gentle giants and solve their soft puzzles.', genres: ['Adventure', 'Puzzle'], tags: ['family', 'fantasy'] },
  { title: 'Circuit City Marathon', description: 'Endless runner through a city that upgrades with you.', genres: ['Arcade', 'Platformer'], tags: ['runner'], endlessStory: true },
  { title: 'Oracle’s Side Quest', description: 'Accept endless side quests from a witty oracle.', genres: ['RPG', 'Adventure'], tags: ['quests'], endlessStory: true },
  { title: 'Tidepool Tactics', description: 'Tiny tactical battles in shifting tide pools.', genres: ['Strategy', 'Arcade'], tags: ['ocean'] },
  { title: 'Firework Architect', description: 'Design firework shows scored by crowd joy.', genres: ['Puzzle', 'Simulation'], tags: ['festival'] },
  { title: 'Silent Snow Rescue', description: 'Find lost travelers in endless blizzard frontiers.', genres: ['Survival', 'Adventure'], tags: ['winter'], endlessStory: true },
  { title: 'Bazaar of Infinite Aisles', description: 'Shopkeeping in a store that grows new floors nightly.', genres: ['Simulation', 'Adventure'], tags: ['shop'], endlessStory: true },
  { title: 'Heroes of Homework Hill', description: 'Turn study sessions into cooperative adventures.', genres: ['Adventure', 'Puzzle'], tags: ['kids', 'education'] },
  { title: 'Crystal Cricket League', description: 'Fantasy cricket with elemental pitches.', genres: ['Sports', 'Fantasy'], tags: ['cricket'] },
  { title: 'Portal Garden Club', description: 'Grow gardens that open to friend dimensions.', genres: ['Simulation', 'Adventure'], tags: ['garden', 'family'] },
];
