/** Polished Free Tier catalog — growth engine (complete games, not demos). */

export type FreeCatalogEntry = {
  slug: string;
  title: string;
  description: string;
  tagline: string;
  genres: string[];
  tags: string[];
  category: 'Arcade' | 'Racing' | 'Puzzle' | 'Action' | 'Adventure';
};

export const FREE_TIER_GAMES: FreeCatalogEntry[] = [
  {
    slug: 'pixel-runner',
    title: 'Pixel Runner',
    description: 'Dash through neon cities, collect gems, and discover secret alleys. Complete and endlessly replayable.',
    tagline: 'Jump. Collect. Never stop.',
    genres: ['Arcade', 'Platformer'],
    tags: ['runner', 'free', 'secrets'],
    category: 'Arcade',
  },
  {
    slug: 'galaxy-defender',
    title: 'Galaxy Defender',
    description: 'Defend the orbital ring from alien fleets. Crystal caches hide among the stars.',
    tagline: 'Hold the perimeter',
    genres: ['Arcade', 'Action', 'Sci-Fi'],
    tags: ['shooter', 'free'],
    category: 'Arcade',
  },
  {
    slug: 'brick-blast',
    title: 'Brick Blast',
    description: 'Shatter luminous brick formations. Rare gold bricks unlock bonus scores.',
    tagline: 'Break everything',
    genres: ['Arcade', 'Puzzle'],
    tags: ['paddle', 'free'],
    category: 'Arcade',
  },
  {
    slug: 'snake-evolution',
    title: 'Snake Evolution',
    description: 'Grow, evolve, and hunt golden relics on a glowing grid.',
    tagline: 'Evolve forever',
    genres: ['Arcade'],
    tags: ['classic', 'free'],
    category: 'Arcade',
  },
  {
    slug: 'neon-drift',
    title: 'Neon Drift',
    description: 'Lane-shift through neon highways with nitro boosts and secret shortcuts.',
    tagline: 'Drift the night',
    genres: ['Racing', 'Arcade'],
    tags: ['racing', 'free'],
    category: 'Racing',
  },
  {
    slug: 'desert-rally',
    title: 'Desert Rally',
    description: 'Sandstorm racing across dunes — dodge rivals and grab oasis coins.',
    tagline: 'Heat and speed',
    genres: ['Racing', 'Arcade'],
    tags: ['racing', 'free'],
    category: 'Racing',
  },
  {
    slug: 'mountain-racer',
    title: 'Mountain Racer',
    description: 'Carve alpine lanes with ice hazards and cliffside nitro.',
    tagline: 'Peak velocity',
    genres: ['Racing', 'Sports'],
    tags: ['racing', 'free'],
    category: 'Racing',
  },
  {
    slug: 'street-sprint',
    title: 'Street Sprint',
    description: 'City block sprints with traffic weave and underground shortcuts.',
    tagline: 'Own the street',
    genres: ['Racing', 'Arcade'],
    tags: ['racing', 'free'],
    category: 'Racing',
  },
  {
    slug: 'ancient-temple',
    title: 'Ancient Temple',
    description: 'Solve trap grids, collect relics, and reach the chamber. A complete puzzle adventure.',
    tagline: 'Mind the traps',
    genres: ['Puzzle', 'Adventure'],
    tags: ['temple', 'free', 'secrets'],
    category: 'Puzzle',
  },
  {
    slug: 'number-master',
    title: 'Number Master',
    description: 'Merge luminous tiles toward 2048 and beyond — polished brain-training forever.',
    tagline: 'Merge to mastery',
    genres: ['Puzzle'],
    tags: ['numbers', 'free'],
    category: 'Puzzle',
  },
  {
    slug: 'logic-blocks',
    title: 'Logic Blocks',
    description: 'Crack hidden color patterns. Perfect solves reveal secret ciphers.',
    tagline: 'Think in color',
    genres: ['Puzzle'],
    tags: ['logic', 'free'],
    category: 'Puzzle',
  },
  {
    slug: 'memory-match',
    title: 'Memory Match',
    description: 'Match neon sigils in a complete memory arena with escalating clears.',
    tagline: 'Remember the pulse',
    genres: ['Puzzle'],
    tags: ['memory', 'free'],
    category: 'Puzzle',
  },
  {
    slug: 'zombie-escape',
    title: 'Zombie Escape',
    description: 'Survive endless undead waves and collect hero cards. Fair challenge, full loops.',
    tagline: 'Survive the night',
    genres: ['Action', 'Horror', 'Survival'],
    tags: ['zombies', 'free'],
    category: 'Action',
  },
  {
    slug: 'shadow-ninja',
    title: 'Shadow Ninja',
    description: 'Swift arena combat with silent strikes and hidden hero cards.',
    tagline: 'Strike unseen',
    genres: ['Action', 'Arcade'],
    tags: ['ninja', 'free'],
    category: 'Action',
  },
  {
    slug: 'alien-attack',
    title: 'Alien Attack',
    description: 'Repel insectoid invaders across crystalline fields.',
    tagline: 'They never stop',
    genres: ['Action', 'Sci-Fi'],
    tags: ['aliens', 'free'],
    category: 'Action',
  },
  {
    slug: 'robot-arena',
    title: 'Robot Arena',
    description: 'Modular mech skirmishes with escalating waves and card drops.',
    tagline: 'Build and battle',
    genres: ['Action', 'Sci-Fi'],
    tags: ['robots', 'free'],
    category: 'Action',
  },
  {
    slug: 'jungle-explorer',
    title: 'Jungle Explorer',
    description: 'Explore living canopies, find treasures, and open hidden chambers.',
    tagline: 'Into the green',
    genres: ['Adventure', 'Arcade'],
    tags: ['explore', 'free', 'secrets'],
    category: 'Adventure',
  },
  {
    slug: 'treasure-hunter',
    title: 'Treasure Hunter',
    description: 'Hunt relics across shifting maps — secrets and rare finds everywhere.',
    tagline: 'Fortune favors the bold',
    genres: ['Adventure'],
    tags: ['treasure', 'free'],
    category: 'Adventure',
  },
  {
    slug: 'lost-kingdom',
    title: 'Lost Kingdom',
    description: 'Wander ruined castles for crystals, cards, and forbidden rooms.',
    tagline: 'Kingdoms forget nothing',
    genres: ['Adventure', 'Fantasy'],
    tags: ['kingdom', 'free', 'secrets'],
    category: 'Adventure',
  },
  {
    slug: 'crystal-quest',
    title: 'Crystal Quest',
    description: 'Gather singing crystals while dodging cave hazards. Full exploration loops.',
    tagline: 'Follow the glow',
    genres: ['Adventure', 'Fantasy'],
    tags: ['crystals', 'free'],
    category: 'Adventure',
  },
  {
    slug: 'color-bus-trip',
    title: 'Color Bus Trip',
    description: 'Hyper-casual color sorting — load matching passenger clusters into the right buses and clear the lot.',
    tagline: 'Match. Board. Depart.',
    genres: ['Puzzle', 'Casual'],
    tags: ['hypercasual', 'color-sort', 'free', 'mobile'],
    category: 'Puzzle',
  },
  {
    slug: 'frost-outpost',
    title: 'Frost Outpost',
    description: 'Arctic survival management — gather wood and food on conveyors, stoke the fire, and endure colder nights.',
    tagline: 'Stay warm. Survive.',
    genres: ['Adventure', 'Casual'],
    tags: ['hypercasual', 'survival', 'management', 'free'],
    category: 'Adventure',
  },
  {
    slug: 'traffic-color-sort',
    title: 'Traffic Color Sort',
    description: 'Send each car to the matching color exit. Fast tap puzzles that ramp every level.',
    tagline: 'One tap. Right lane.',
    genres: ['Puzzle', 'Casual'],
    tags: ['hypercasual', 'color-sort', 'free'],
    category: 'Puzzle',
  },
  {
    slug: 'belt-kitchen',
    title: 'Belt Kitchen',
    description: 'Prep, cook, and ship orders down the conveyor before the shift timer hits zero.',
    tagline: 'Cook the rush',
    genres: ['Arcade', 'Casual'],
    tags: ['hypercasual', 'idle', 'free'],
    category: 'Arcade',
  },
];

export const FREE_TIER_SLUGS = FREE_TIER_GAMES.map((g) => g.slug);
