import type { Game } from '@/lib/api';
import { SIGNATURE_ORIGINALS, buildExpandedCatalog } from '@games/catalog/jgames-200';

/** Classic free arcade set */
const CLASSICS: Game[] = [
  {
    id: 'space-defender',
    slug: 'space-defender',
    title: 'Space Defender',
    description: 'Defend the orbital ring from waves of neon invaders.',
    genres: ['Arcade', 'Action', 'Sci-Fi'],
    tags: ['shooter'],
    access: 'FREE',
    creditCost: 0,
    featured: true,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'pixel-runner',
    slug: 'pixel-runner',
    title: 'Pixel Runner',
    description: 'Dash through procedural neon cities forever.',
    genres: ['Arcade', 'Platformer'],
    tags: ['runner'],
    access: 'FREE',
    creditCost: 0,
    featured: true,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'galaxy-assault',
    slug: 'galaxy-assault',
    title: 'Galaxy Assault',
    description: 'Top-down starfield combat with escalating fleets.',
    genres: ['Action', 'Sci-Fi'],
    tags: ['shooter'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'snake-evolution',
    slug: 'snake-evolution',
    title: 'Snake Evolution',
    description: 'Grow and outmaneuver in a glowing grid arena.',
    genres: ['Arcade'],
    tags: ['classic'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'brick-destroyer',
    slug: 'brick-destroyer',
    title: 'Brick Destroyer',
    description: 'Shatter luminous brick formations.',
    genres: ['Arcade', 'Puzzle'],
    tags: ['paddle'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'maze-escape',
    slug: 'maze-escape',
    title: 'Maze Escape',
    description: 'Procedural labyrinths that rewrite each run.',
    genres: ['Adventure', 'Puzzle'],
    tags: ['maze'],
    access: 'FREE',
    creditCost: 0,
    featured: true,
    trending: false,
    endlessStory: true,
  },
  {
    id: 'tank-arena',
    slug: 'tank-arena',
    title: 'Tank Arena',
    description: 'Tactical arena duels with destructible neon cover.',
    genres: ['Action', 'Strategy'],
    tags: ['arena'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'alien-blaster',
    slug: 'alien-blaster',
    title: 'Alien Blaster',
    description: 'Rapid-fire insectoid swarms across crystalline caverns.',
    genres: ['Action', 'Horror'],
    tags: ['blaster'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'sky-shooter',
    slug: 'sky-shooter',
    title: 'Sky Shooter',
    description: 'Aerial dogfights above luminous cloud cities.',
    genres: ['Action', 'Arcade'],
    tags: ['flight'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'fruit-slice',
    slug: 'fruit-slice',
    title: 'Fruit Slice',
    description: 'Slice cascading fruit with precise swipes.',
    genres: ['Arcade'],
    tags: ['swipe'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'tower-defender',
    slug: 'tower-defender',
    title: 'Tower Defender',
    description: 'Hold the gate against endless waves.',
    genres: ['Strategy', 'Arcade'],
    tags: ['tower'],
    access: 'FREE',
    creditCost: 0,
    featured: true,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'endless-racer',
    slug: 'endless-racer',
    title: 'Endless Racer',
    description: 'Lane-shift forever through neon highways.',
    genres: ['Racing', 'Arcade'],
    tags: ['racing'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'zombie-survival',
    slug: 'zombie-survival',
    title: 'Zombie Survival',
    description: 'Survive night raids in a fortified outpost.',
    genres: ['Survival', 'Horror', 'Action'],
    tags: ['zombies'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'word-puzzle',
    slug: 'word-puzzle',
    title: 'Word Puzzle',
    description: 'Find words in shifting letter grids.',
    genres: ['Puzzle'],
    tags: ['words'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'sudoku',
    slug: 'sudoku',
    title: 'Sudoku',
    description: 'Classic number logic on a luminous board.',
    genres: ['Puzzle'],
    tags: ['logic'],
    access: 'FREE',
    creditCost: 0,
    featured: true,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'chess',
    slug: 'chess',
    title: 'Chess',
    description: 'Classic chess with a neon board aesthetic.',
    genres: ['Strategy'],
    tags: ['board'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'checkers',
    slug: 'checkers',
    title: 'Checkers',
    description: 'Fast checkers duels on a glowing checkerboard.',
    genres: ['Strategy'],
    tags: ['board'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'twenty-forty-eight',
    slug: 'twenty-forty-eight',
    title: '2048',
    description: 'Merge luminous tiles toward 2048 and beyond.',
    genres: ['Puzzle'],
    tags: ['merge'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'bubble-pop',
    slug: 'bubble-pop',
    title: 'Bubble Pop',
    description: 'Aim and pop chromatic bubble clusters.',
    genres: ['Puzzle', 'Arcade'],
    tags: ['bubbles'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'memory-match',
    slug: 'memory-match',
    title: 'Memory Match',
    description: 'Match pairs of original neon sigils.',
    genres: ['Puzzle'],
    tags: ['memory'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
];

function toGame(g: {
  slug: string;
  title: string;
  description: string;
  genres: string[];
  tags: string[];
  access: 'FREE' | 'PREMIUM' | 'CREDITS';
  creditCost: number;
  featured?: boolean;
  trending?: boolean;
  endlessStory?: boolean;
}): Game {
  return {
    id: g.slug,
    slug: g.slug,
    title: g.title,
    description: g.description,
    genres: g.genres,
    tags: g.tags,
    access: g.access,
    creditCost: g.creditCost,
    featured: !!g.featured,
    trending: !!g.trending,
    endlessStory: !!g.endlessStory,
  };
}

const classicSlugs = CLASSICS.map((g) => g.slug);
const expanded = buildExpandedCatalog(classicSlugs);

/** Full client catalog fallback (~200) for offline / API-down play browsing */
export const FREE_GAME_CATALOG: Game[] = [
  ...CLASSICS,
  ...SIGNATURE_ORIGINALS.map(toGame),
  ...expanded.filter((g) => !SIGNATURE_ORIGINALS.some((s) => s.slug === g.slug)).map(toGame),
];

/** Playable free + signature titles for static generation */
export const PLAYABLE_FREE_SLUGS = [
  ...CLASSICS.map((g) => g.slug),
  ...SIGNATURE_ORIGINALS.map((g) => g.slug),
];

export const STORY_MODE = SIGNATURE_ORIGINALS.find((g) => g.slug === 'rise-of-the-forgotten-king')!;

export const GENRES = [
  'Adventure',
  'RPG',
  'Strategy',
  'Simulation',
  'Puzzle',
  'Arcade',
  'Sports',
  'Horror',
  'Fantasy',
  'Sci-Fi',
  'Racing',
  'Survival',
  'Action',
  'Platformer',
  'Idle',
  'MMORPG',
];
