import type { Game } from '@/lib/api';

/** Client-side catalog fallback — mirrors seeded free games for instant play */
export const FREE_GAME_CATALOG: Game[] = [
  {
    id: 'space-defender',
    slug: 'space-defender',
    title: 'Space Defender',
    description: 'Defend the orbital ring from waves of neon invaders.',
    genres: ['Arcade', 'Action', 'Sci-Fi'],
    tags: ['shooter'],
    access: 'FREE',
    creditCost: 0,
    featured: true,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'pixel-runner',
    slug: 'pixel-runner',
    title: 'Pixel Runner',
    description: 'Dash through procedural neon cities forever.',
    genres: ['Arcade', 'Platformer'],
    tags: ['runner'],
    access: 'FREE',
    creditCost: 0,
    featured: true,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'galaxy-assault',
    slug: 'galaxy-assault',
    title: 'Galaxy Assault',
    description: 'Top-down starfield combat with escalating fleets.',
    genres: ['Action', 'Sci-Fi'],
    tags: ['shooter'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'snake-evolution',
    slug: 'snake-evolution',
    title: 'Snake Evolution',
    description: 'Grow and outmaneuver in a glowing grid arena.',
    genres: ['Arcade'],
    tags: ['classic'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'brick-destroyer',
    slug: 'brick-destroyer',
    title: 'Brick Destroyer',
    description: 'Shatter luminous brick formations.',
    genres: ['Arcade', 'Puzzle'],
    tags: ['paddle'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'maze-escape',
    slug: 'maze-escape',
    title: 'Maze Escape',
    description: 'Procedural labyrinths that rewrite each run.',
    genres: ['Adventure', 'Puzzle'],
    tags: ['maze'],
    access: 'FREE',
    creditCost: 0,
    featured: true,
    trending: false,
    endlessStory: true,
  },
  {
    id: 'tank-arena',
    slug: 'tank-arena',
    title: 'Tank Arena',
    description: 'Tactical arena duels with neon cover.',
    genres: ['Action', 'Strategy'],
    tags: ['arena'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'alien-blaster',
    slug: 'alien-blaster',
    title: 'Alien Blaster',
    description: 'Rapid-fire swarms across crystalline caverns.',
    genres: ['Action', 'Horror'],
    tags: ['blaster'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'sky-shooter',
    slug: 'sky-shooter',
    title: 'Sky Shooter',
    description: 'Soar through storm fronts and clear the skies.',
    genres: ['Arcade', 'Action'],
    tags: ['flight'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'fruit-slice',
    slug: 'fruit-slice',
    title: 'Fruit Slice',
    description: 'Slice cascading fruit orbs — avoid void bombs.',
    genres: ['Arcade'],
    tags: ['reflex'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'tower-defender',
    slug: 'tower-defender',
    title: 'Tower Defender',
    description: 'Place energy towers and hold the lane.',
    genres: ['Strategy', 'Survival'],
    tags: ['tower'],
    access: 'FREE',
    creditCost: 0,
    featured: true,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'endless-racer',
    slug: 'endless-racer',
    title: 'Endless Racer',
    description: 'Neon highway racing with reactive traffic.',
    genres: ['Racing', 'Arcade'],
    tags: ['racing'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'zombie-survival',
    slug: 'zombie-survival',
    title: 'Zombie Survival',
    description: 'Nightfall horde survival with crafting scraps.',
    genres: ['Survival', 'Horror'],
    tags: ['survival'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'word-puzzle',
    slug: 'word-puzzle',
    title: 'Word Puzzle',
    description: 'Assemble luminous letters into words.',
    genres: ['Puzzle'],
    tags: ['words'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'sudoku',
    slug: 'sudoku',
    title: 'Sudoku',
    description: 'Number grids with elegant neon UI.',
    genres: ['Puzzle'],
    tags: ['logic'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'chess',
    slug: 'chess',
    title: 'Chess',
    description: 'Original chess with cinematic board lighting.',
    genres: ['Strategy', 'Puzzle'],
    tags: ['board'],
    access: 'FREE',
    creditCost: 0,
    featured: true,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'checkers',
    slug: 'checkers',
    title: 'Checkers',
    description: 'Fast checkers on a glowing board.',
    genres: ['Strategy'],
    tags: ['board'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'twenty-forty-eight',
    slug: 'twenty-forty-eight',
    title: '2048',
    description: 'Merge luminous tiles toward 2048 and beyond.',
    genres: ['Puzzle'],
    tags: ['merge'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: true,
    endlessStory: false,
  },
  {
    id: 'bubble-pop',
    slug: 'bubble-pop',
    title: 'Bubble Pop',
    description: 'Aim and pop chromatic bubble clusters.',
    genres: ['Puzzle', 'Arcade'],
    tags: ['bubbles'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
  {
    id: 'memory-match',
    slug: 'memory-match',
    title: 'Memory Match',
    description: 'Match pairs of original neon sigils.',
    genres: ['Puzzle'],
    tags: ['memory'],
    access: 'FREE',
    creditCost: 0,
    featured: false,
    trending: false,
    endlessStory: false,
  },
];

export const GENRES = [
  'Adventure',
  'RPG',
  'Strategy',
  'Simulation',
  'Puzzle',
  'Arcade',
  'Sports',
  'Horror',
  'Fantasy',
  'Sci-Fi',
  'Racing',
  'Survival',
  'Action',
  'Platformer',
  'Idle',
  'MMORPG',
];
